### ISSUE TITLE
Fase Previa

### ISSUE THREAD

**Issue by Bufigol** [Bufigol/YeepApp#1]
Se debe definir la paleta de colores de la app en conjunto al logo y a los iconos que van a utilizar.

**Comment by josemanuelCRV** [comment]
-INTERFACE-------------------------------------------------
- Nuevo nombre de App _-_WICK_-_
- Nuevas imágenes /drawable/ backgrounds - icons.
- Nuevos colores de paleta RED
- Editados layouts Login y SinUp
- Editado archivo @colors
- Editado archivo @dimen
- Nueva disposición de los componentes sobre los layout
