### ISSUE TITLE
Seleccionar Amigos

### ISSUE THREAD

**Issue by Bufigol** [Bufigol/YeepApp#15]
Seleccionar amigos de de la lista y guardar las relaciones en Parse.

**Comment by josemanuelCRV** [comment]
## onListItemClick realiza dos funciones: 

---

Seleccionando amigos de la lista:

---
- seleccionar o deseleccionar una fila , activando checks multiples con la sentencia 
  getListView().setChoiceMode(ListView.CHOICE_MODE_MULTIPLE) 
- y   por otro lado, estableceremos o no una relación con   Parse Relation.

---

Guardando relaciones de amigos:

---
- ParseRelation<ParseUser>   relación de objetos ParseRelation  con objeto usuario actual.
  mCurrentUser = ParseUser.getCurrentUser();
- Instanciar la relación mediante el método getRelation.
  mFriendsRelation = mCurrentUser.getRelation("friendsRelation").
-  Declaración del nombre de la relación en constante  KEY_FRIENDS_RELATION.
-   Añadir una relación -->  mFriendsRelation.add(mUsers.get(position));
-  Log  y AlertDialog para el control de errores.
