### ISSUE TITLE
Eliminar Amigos

### ISSUE THREAD

**Issue by Bufigol** [Bufigol/YeepApp#16]
De la lista de amigos existente, eliminar un usuario como amigo y registrar acción en parse.

**Comment by josemanuelCRV** [comment]
Eliminando de nuestra lista de amigos:

---

## Eliminando de nuestra lista de amigos

-Modificado el método onListItemClick.
-Borrar un usuario método remove
   mFriendsRelation.remove(mUsers.get(position)).

---

Añadiendo checks … cuando la lista está cargada

---
- Sobre metodo onResume,  objectIds guarda los id de los usuarios en un ArrayList.
-  Nuevo metodo addFriendCheckmarks:
  - Obtiene las relaciones del usuario actual

---

Mostrando nuestra lista de amigos

---
- Muestra los usuarios en relación con el usuario actual y el adaptador utilizará el
  layout android.R.layout.simple_list_item_1.
