### ISSUE TITLE
ProgressBar &Personalización ActionBar

### ISSUE THREAD

**Issue by Bufigol** [Bufigol/YeepApp#17]
- Implantación de ProgressBar en ActionBar de la actividad de LogIn. 
- Personalización ActionBar Tabs existentes en los fragmentos que aparcecen en Main Activty

**Comment by josemanuelCRV** [comment]
ProgressBar + Personalización del ActionBar Tabs :

Implementado ProgressBar sobre ActionBar en pantalla Login :
ActionBar sólo es mostrado cuando los campos de usuario y contraseña son ingresados y se inicia el login.
ProgressBar es mostrado sobre el ActionBar mientras se realiza la acción. Una vez terminada la acción se oculta de nuevo el ActionBar.

Personalizado el ActionBar Tabs: 
ActionBar Tabs pasa a tener dos pestañas, INBOX / FRIENDS. 
Sustituido el texto de las pestañas por dos iconos (archive & people).
