### ISSUE TITLE
Mostrar Users

### ISSUE THREAD

**Issue by ghost** [Bufigol/YeepApp#18]

**Comment by josemanuelCRV** [comment]
## Novedades:

Nueva sección en el menú principal. -- Edit Friend.
Asociada a nueva clase  EditFriendsActivity . class y nuevo layout  EditFriendsActivity.
EditFriendsActivity  cuenta con ListView para mostrar todos los amigos y un ProgressBar indicando la ejecución de la consulta en curso.

## Configurando una consulta para usuarios:

Consulta en  - onResume -  llamado siempre que la actividad es mostrada.  
Obtener todos los usuarios añadidos  ParseQuery query = ParseUser.getQuery();
Realizar consulta en segundo plano mediante el método findInBackground y el
callback FindCallback.
Instanciados nuevos miembros, List de objetos ParseUsers, ArrayList de Strings y ArrayAdapter de String.
