### ISSUE TITLE
Hacer vídeo mediante Intent.

### ISSUE THREAD

**Issue by ghost** [Bufigol/YeepApp#23]

**Comment by josemanuelCRV** [comment]
## Hacer una vídeo mediante un Intent y Almacenarlo en la memoria:

Ediciones realizadas:

---

<b>MainActivity </b>

---

En el método mDialogListener() :
se ha creado en la opción 1 un nuevo intent llamado takeVideoIntent que recibe por parámetro en el constructor la constante MediaStore.ACTION_VIDEO_CAPTURE .

   Intent takeVideoIntent = new Intent(MediaStore.ACTION_VIDEO_CAPTURE);

se almacena en mMediaUri  la Uri que devuelve el método:
mMediaUri = FileUtilities.getOutputMediaFileUri(FileUtilities.MEDIA_TYPE_VIDEO);

En el caso de no contener nada  mMediaUri ,  se mostrará un mensaje de  error.
De lo contrario, añadiremos la siguiente información  extra al Intent con putExtra():
- EXTRA_OUTPUT
- EXTRA_DURATION_LIMIT  -->  establecido el limite de grabación a 10 segundos.
- EXTRA_VIDEO_QUALITY  -->    establecido calidad del video a la mínima.

El método  startActivityForResult():
Recibe por parámetro el intent que acabamos de crear y un número que lo identifica: TAKE_VIDEO_REQUEST
