### ISSUE TITLE
Logueo app

### ISSUE THREAD

**Issue by Bufigol** [Bufigol/YeepApp#7]
Loguearse en la aplicación mediante Parse

**Comment by josemanuelCRV** [comment]
Desarrollado login de usuario en Parse.com
*\* Por realizar test sobre distintos dispositivos móviles.

**Comment by Bufigol** [comment]
Hay que revisar la comprobación de datos y el intent a la activity correspondiente.

**Comment by Bufigol** [comment]
Ya se ha incorporado información de otras ramas. Falta por desarrollar mas comprobaciones para un correcto log in.
